[master]
timer-size = 60
port = 35353

[server-selection]
enabled = true
strategy = "lowest_tick_time"

[drain-server]
enabled = true
port = 8080
strategy = "default"

[scaling]
strategy = "none" # none means no scaling
interval = 60

[migration]
strategy = "none" # none means no migration
interval = 60
