[master]
port = 35353

[server-selection]
enabled = true
#strategy = "lowest_tick_time"
strategy = "weighted_tick_players"
timeW = 5.0
playerW = 1.0

[drain-server]
enabled = true
port = 8080
strategy = "default"

[scaling]
enabled = true
strategy = "none" # none means no scaling
#strategy = "tick_length_v2"
scaling-interval = 30
scaleUpRatio = 0.3
scaleDownRatio = 0.2

[performance.tick_length]
low = 11
high = 41

[migration]
# none means no migration
#strategy = "none" 
strategy = "easy_strategy"
# red level, scale up
redL = 0.6
interval = 10
units = "SECONDS"
# players to transfer
playersT = 0.2


